plugins {
	id 'io.spring.convention.integration-test'
}

apply plugin: 'java'
apply plugin: 'groovy'

repositories {
	mavenLocal()
	maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
	maven { url 'https://maven.aliyun.com/repository/public/' }
}

dependencies {
	testCompile 'junit:junit:4.12'
	testCompile 'org.spockframework:spock-core:1.0-groovy-2.4'
	integrationTestCompile 'org.springframework:spring-core:4.3.7.RELEASE'
}
