plugins {
	id 'io.spring.convention.integration-test'
}

apply plugin: 'java'

repositories {
	mavenLocal()
	maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
	maven { url 'https://maven.aliyun.com/repository/public/' }
}

dependencies {
	optional 'jakarta.servlet:jakarta.servlet-api:5.0.0'
	testCompile 'junit:junit:4.12'
}
