plugins {
	id 'io.spring.convention.spring-module'
}

repositories {
	mavenLocal()
	maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
	maven { url 'https://maven.aliyun.com/repository/public/' }
}

dependencies {
	testCompile 'junit:junit:4.12'
	compile 'org.springframework:spring-core'
}
